language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9
env:
- HADOOP_DISTRO=cdh HADOOP_HOME=/tmp/hadoop-cdh
- HADOOP_DISTRO=hdp HADOOP_HOME=/tmp/hadoop-hdp
sudo: false
branches:
  except:
    - gh-pages
script:
  - pip install -r requirements-dev.txt
  - scripts/ci/setup_env.sh
  - nosetests -v
