language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9
jobs:
  allow_failures:
    - python: 
      - "3.8"
      - "3.9"
jdk: oraclejdk7
sudo: false
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py34-cdh
  - TOX_ENV=py34-hdp
install:
  - pip install tox
script:
  - tox --version
  - python setup.py test --tox-args="-e $TOX_ENV"
